// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package resource

import (
	"context"

	"wdkr-marketplace-service/internal/cron"
	"wdkr-marketplace-service/internal/domain/cart"
	cartrepo "wdkr-marketplace-service/internal/domain/cart/repo"
	"wdkr-marketplace-service/internal/domain/ecoin"
	ecoinrepo "wdkr-marketplace-service/internal/domain/ecoin/repo"
	"wdkr-marketplace-service/internal/domain/order"
	orderrepo "wdkr-marketplace-service/internal/domain/order/repo"
	"wdkr-marketplace-service/internal/domain/payment"
	paymentrepo "wdkr-marketplace-service/internal/domain/payment/repo"
	"wdkr-marketplace-service/internal/domain/sku"
	skurepo "wdkr-marketplace-service/internal/domain/sku/repo"
	"wdkr-marketplace-service/internal/domain/user"
	userrepo "wdkr-marketplace-service/internal/domain/user/repo"
	"wdkr-marketplace-service/internal/resource/healthy"
	"wdkr-marketplace-service/internal/resource/marketplace"
	"wdkr-marketplace-service/internal/resource/mock"
	"wdkr-marketplace-service/internal/resource/openapi"
	"wdkr-marketplace-service/internal/resource/ops"
)

// userServiceAdapter 适配 user.UserService 到 order.UserServiceForOrder
type userServiceAdapter struct {
	userSvc user.UserService
}

func (a *userServiceAdapter) GetBindingsByUserId(ctx context.Context, userId uint) ([]order.UserBinding, error) {
	bindings, err := a.userSvc.GetBindingsByUserId(ctx, userId)
	if err != nil {
		return nil, err
	}
	result := make([]order.UserBinding, len(bindings))
	for i, b := range bindings {
		result[i] = order.UserBinding{
			BizCode:   b.BizCode,
			BizUserId: b.BizUserId,
		}
	}
	return result, nil
}

// InitializeResources 初始化所有 Resources
func InitializeResources() *Resources {
	// 初始化 Repos
	skuRepo := skurepo.NewSkuRepo()
	orderRepo := orderrepo.NewOrderRepo()
	paymentRepo := paymentrepo.NewPaymentRepo()
	ecoinRepo := ecoinrepo.NewEcoinRepo()
	userRepo := userrepo.NewUserRepo()
	userBindingRepo := userrepo.NewUserBindingRepo()
	cartRepo := cartrepo.NewCartRepo()

	// 初始化支付渠道
	wechatPayConfig := payment.NewWechatPayConfig()
	wechatPayChannel := payment.NewWechatPayChannel(wechatPayConfig)
	paymentChannels := payment.ProvidePaymentChannels(wechatPayChannel)

	// 初始化 Services
	ecoinService := ecoin.NewEcoinService(ecoinRepo)
	skuService := sku.NewSkuService(skuRepo)
	paymentService := payment.ProvidePaymentService(paymentRepo, paymentChannels)
	userService := user.NewUserService(userRepo, userBindingRepo, ecoinService)
	userSvcAdapter := &userServiceAdapter{userSvc: userService}
	orderService := order.NewOrderService(orderRepo, skuService, ecoinService, paymentService, userSvcAdapter)
	cartService := cart.NewCartService(cartRepo, skuService, orderService)

	// 初始化 Resources
	healthyResource := healthy.NewHealthyResource()
	marketplaceResource := marketplace.NewMarketplaceResource(skuService, orderService, ecoinService, userService, cartService)
	opsResource := ops.NewOpsResource(skuService, orderService)
	openAPIResource := openapi.NewOpenAPIResource(ecoinService, paymentService, userService, orderService)
	mockResource := mock.NewMockResource()

	// 初始化定时任务
	orderTimeoutTask := cron.NewOrderTimeoutTask(orderRepo, paymentService)
	orderFulfillTask := cron.NewOrderFulfillTask(orderRepo, orderService)

	// 聚合返回
	r := NewResources(healthyResource, marketplaceResource, opsResource, openAPIResource, orderTimeoutTask, orderFulfillTask)
	r.Mock = mockResource
	return r
}
