// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package resource

import (
	"context"
	"errors"

	"wdkr-marketplace-service/internal/cron"
	bizcoderepo "wdkr-marketplace-service/internal/domain/bizcode/repo"
	"wdkr-marketplace-service/internal/domain/cart"
	cartrepo "wdkr-marketplace-service/internal/domain/cart/repo"
	companyrepo "wdkr-marketplace-service/internal/domain/company/repo"
	"wdkr-marketplace-service/internal/domain/companyecoin"
	companyecoinrepo "wdkr-marketplace-service/internal/domain/companyecoin/repo"
	"wdkr-marketplace-service/internal/domain/ecoin"
	ecoinrepo "wdkr-marketplace-service/internal/domain/ecoin/repo"
	"wdkr-marketplace-service/internal/domain/ecoinbill"
	ecoinbillrepo "wdkr-marketplace-service/internal/domain/ecoinbill/repo"
	"wdkr-marketplace-service/internal/domain/order"
	orderrepo "wdkr-marketplace-service/internal/domain/order/repo"
	"wdkr-marketplace-service/internal/domain/payment"
	paymentrepo "wdkr-marketplace-service/internal/domain/payment/repo"
	"wdkr-marketplace-service/internal/domain/sku"
	skurepo "wdkr-marketplace-service/internal/domain/sku/repo"
	"wdkr-marketplace-service/internal/domain/user"
	userrepo "wdkr-marketplace-service/internal/domain/user/repo"
	"wdkr-marketplace-service/internal/resource/healthy"
	"wdkr-marketplace-service/internal/resource/marketplace"
	"wdkr-marketplace-service/internal/resource/mock"
	"wdkr-marketplace-service/internal/resource/openapi"
	"wdkr-marketplace-service/internal/resource/ops"
)

// userServiceAdapter 适配 user.UserService 到 order.UserServiceForOrder
type userServiceAdapter struct {
	userSvc user.UserService
}

func (a *userServiceAdapter) GetBindingsByUserId(ctx context.Context, userId uint) ([]order.UserBinding, error) {
	bindings, err := a.userSvc.GetBindingsByUserId(ctx, userId)
	if err != nil {
		return nil, err
	}
	result := make([]order.UserBinding, len(bindings))
	for i, b := range bindings {
		result[i] = order.UserBinding{
			BizCode:   b.BizCode,
			BizUserId: b.BizUserId,
		}
	}
	return result, nil
}

func (a *userServiceAdapter) GetUserCompanyId(ctx context.Context, userId uint) (uint64, error) {
	u, err := a.userSvc.GetUserById(ctx, userId)
	if err != nil {
		return 0, err
	}
	if u == nil {
		return 0, errors.New("user not found")
	}
	return u.CompanyId, nil
}

// InitializeResources 初始化所有 Resources
func InitializeResources() *Resources {
	// 初始化 Repos
	skuRepo := skurepo.NewSkuRepo()
	orderRepo := orderrepo.NewOrderRepo()
	paymentRepo := paymentrepo.NewPaymentRepo()
	ecoinRepo := ecoinrepo.NewEcoinRepo()
	userRepo := userrepo.NewUserRepo()
	userBindingRepo := userrepo.NewUserBindingRepo()
	cartRepo := cartrepo.NewCartRepo()
	bizCodeRepo := bizcoderepo.NewBizCodeRepo()
	companyRepo := companyrepo.NewCompanyRepo()
	companyEcoinRepo := companyecoinrepo.NewCompanyEcoinRepo()
	pointsBillRepo := ecoinbillrepo.NewEcoinBillRepo()

	// 初始化支付渠道
	wechatPayConfig := payment.NewWechatPayConfig()
	wechatPayChannel := payment.NewWechatPayChannel(wechatPayConfig)
	paymentChannels := payment.ProvidePaymentChannels(wechatPayChannel)

	// 初始化 Services
	ecoinService := ecoin.NewEcoinService(ecoinRepo)
	companyEcoinService := companyecoin.NewCompanyEcoinService(companyEcoinRepo)
	skuService := sku.NewSkuService(skuRepo)
	paymentService := payment.ProvidePaymentService(paymentRepo, paymentChannels)
	userService := user.NewUserService(userRepo, userBindingRepo, ecoinService, companyEcoinService, companyRepo, bizCodeRepo)
	userSvcAdapter := &userServiceAdapter{userSvc: userService}
	orderService := order.NewOrderService(orderRepo, skuService, ecoinService, companyEcoinService, paymentService, userSvcAdapter)
	cartService := cart.NewCartService(cartRepo, skuService, orderService)
	pointsBillService := ecoinbill.NewEcoinBillService(pointsBillRepo, ecoinService, companyEcoinService)

	// 初始化 Resources
	healthyResource := healthy.NewHealthyResource()
	marketplaceResource := marketplace.NewMarketplaceResource(skuService, orderService, ecoinService, companyEcoinService, userService, cartService, bizCodeRepo, companyRepo)
	opsResource := ops.NewOpsResource(skuService, orderService, userService, ecoinService, companyEcoinService)
	openAPIResource := openapi.NewOpenAPIResource(ecoinService, companyEcoinService, paymentService, orderService, userService, pointsBillService)
	mockResource := mock.NewMockResource()

	// 初始化定时任务
	orderTimeoutTask := cron.NewOrderTimeoutTask(orderRepo, paymentService)
	orderFulfillTask := cron.NewOrderFulfillTask(orderRepo, orderService)
	ecoinExpireTask := cron.NewEcoinExpireTask(ecoinService, companyEcoinService)
	pointsBillAutoCancelTask := cron.NewEcoinBillAutoCancelTask(pointsBillService)

	// 聚合返回
	r := NewResources(healthyResource, marketplaceResource, opsResource, openAPIResource, orderTimeoutTask, orderFulfillTask, ecoinExpireTask, pointsBillAutoCancelTask)
	r.Mock = mockResource
	return r
}
