// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package resource

import (
	"wdkr-marketplace-service/internal/domain/ecoin"
	ecoinrepo "wdkr-marketplace-service/internal/domain/ecoin/repo"
	"wdkr-marketplace-service/internal/domain/order"
	orderrepo "wdkr-marketplace-service/internal/domain/order/repo"
	"wdkr-marketplace-service/internal/domain/payment"
	paymentrepo "wdkr-marketplace-service/internal/domain/payment/repo"
	"wdkr-marketplace-service/internal/domain/sku"
	skurepo "wdkr-marketplace-service/internal/domain/sku/repo"
	"wdkr-marketplace-service/internal/domain/user"
	userrepo "wdkr-marketplace-service/internal/domain/user/repo"
	"wdkr-marketplace-service/internal/resource/healthy"
	"wdkr-marketplace-service/internal/resource/marketplace"
	"wdkr-marketplace-service/internal/resource/openapi"
	"wdkr-marketplace-service/internal/resource/ops"
)

// InitializeResources 初始化所有 Resources
func InitializeResources() *Resources {
	// 初始化 Repos
	skuRepo := skurepo.NewSkuRepo()
	orderRepo := orderrepo.NewOrderRepo()
	paymentRepo := paymentrepo.NewPaymentRepo()
	ecoinRepo := ecoinrepo.NewEcoinRepo()
	userRepo := userrepo.NewUserRepo()
	userBindingRepo := userrepo.NewUserBindingRepo()

	// 初始化支付渠道
	wechatPayConfig := payment.NewWechatPayConfig()
	wechatPayChannel := payment.NewWechatPayChannel(wechatPayConfig)
	paymentChannels := payment.ProvidePaymentChannels(wechatPayChannel)

	// 初始化 Services
	ecoinService := ecoin.NewEcoinService(ecoinRepo)
	skuService := sku.NewSkuService(skuRepo)
	paymentService := payment.ProvidePaymentService(paymentRepo, paymentChannels)
	orderService := order.NewOrderService(orderRepo, skuService, ecoinService, paymentService)
	userService := user.NewUserService(userRepo, userBindingRepo, ecoinService)

	// 初始化 Resources
	healthyResource := healthy.NewHealthyResource()
	marketplaceResource := marketplace.NewMarketplaceResource(skuService, orderService, ecoinService, userService)
	opsResource := ops.NewOpsResource(skuService, orderService)
	openAPIResource := openapi.NewOpenAPIResource(ecoinService, paymentService, userService)

	// 聚合返回
	resources := NewResources(healthyResource, marketplaceResource, opsResource, openAPIResource)
	return resources
}
